# TODO: We should be obtaining this metadata directly from the api repository.
schemas:

  - type: "virtual-service"
    plural: "virtual-services"
    group: "networking"
    version: "v1alpha3"
    messageName: "istio.networking.v1alpha3.VirtualService"
    collection: "istio/networking/v1alpha3/virtualservices"
    description: "describes v1alpha3 route rules"

  - type: "gateway"
    plural: "gateways"
    group: "networking"
    version: "v1alpha3"
    messageName: "istio.networking.v1alpha3.Gateway"
    collection: "istio/networking/v1alpha3/gateways"
    description: "describes a gateway (how a proxy is exposed on the network)"

  - type: "service-entry"
    plural: "service-entries"
    group: "networking"
    version: "v1alpha3"
    messageName: "istio.networking.v1alpha3.ServiceEntry"
    collection: "istio/networking/v1alpha3/serviceentries"
    description: "describes service entries"

  - type: "synthetic-service-entry"
    plural: "synthetic-service-entries"
    group: "networking"
    version: "v1alpha3"
    clusterScoped: true
    messageName: "istio.networking.v1alpha3.ServiceEntry"
    collection: "istio/networking/v1alpha3/synthetic/serviceentries"
    description: "describes synthetic service entries"

  - type: "destination-rule"
    plural: "destination-rules"
    group: "networking"
    version: "v1alpha3"
    messageName: "istio.networking.v1alpha3.DestinationRule"
    collection: "istio/networking/v1alpha3/destinationrules"
    description: "describes destination rules"

  - type: "envoy-filter"
    plural: "envoy-filters"
    group: "networking"
    version: "v1alpha3"
    messageName: "istio.networking.v1alpha3.EnvoyFilter"
    collection: "istio/networking/v1alpha3/envoyfilters"
    description: "describes additional envoy filters to be inserted by Pilot"

  - type: "sidecar"
    plural: "sidecars"
    group: "networking"
    version: "v1alpha3"
    messageName: "istio.networking.v1alpha3.Sidecar"
    collection: "istio/networking/v1alpha3/sidecars"
    description: "describes the listeners associated with sidecars in a namespace"

  - type: "http-api-spec"
    plural: "http-api-specs"
    group: "config"
    version: "v1alpha2"
    messageName: "istio.mixer.v1.config.client.HTTPAPISpec"
    collection: "istio/config/v1alpha2/httpapispecs"
    variableName: "HTTPAPISpec"
    description: "describes an HTTP API specification."

  - type: "http-api-spec-binding"
    plural: "http-api-spec-bindings"
    group: "config"
    version: "v1alpha2"
    messageName: "istio.mixer.v1.config.client.HTTPAPISpecBinding"
    collection: "istio/config/v1alpha2/httpapispecbindings"
    variableName: "HTTPAPISpecBinding"
    description: "describes an HTTP API specification binding."

  - type: "quota-spec"
    plural: "quota-specs"
    group: "config"
    version: "v1alpha2"
    messageName: "istio.mixer.v1.config.client.QuotaSpec"
    collection: "istio/mixer/v1/config/client/quotaspecs"
    description: "describes an Quota specification."

  - type: "quota-spec-binding"
    plural: "quota-spec-bindings"
    group: "config"
    version: "v1alpha2"
    messageName: "istio.mixer.v1.config.client.QuotaSpecBinding"
    collection: "istio/mixer/v1/config/client/quotaspecbindings"
    description: "describes an Quota specification binding."

  - type: "policy"
    plural: "policies"
    group: "authentication"
    version: "v1alpha1"
    messageName: "istio.authentication.v1alpha1.Policy"
    converter: "auth-policy-resource"
    collection: "istio/authentication/v1alpha1/policies"
    variableName: "AuthenticationPolicy"
    description: "describes an authentication policy."

  - type: "mesh-policy"
    plural: "mesh-policies"
    group: "authentication"
    version: "v1alpha1"
    messageName: "istio.authentication.v1alpha1.Policy"
    converter: "auth-policy-resource"
    collection: "istio/authentication/v1alpha1/meshpolicies"
    clusterScoped: true
    variableName: "AuthenticationMeshPolicy"
    validate: "ValidateAuthenticationPolicy"
    description: "describes an authentication policy at mesh level."

  - type: "service-role"
    plural: "service-roles"
    group: "rbac"
    version: "v1alpha1"
    messageName: "istio.rbac.v1alpha1.ServiceRole"
    collection: "istio/rbac/v1alpha1/serviceroles"
    description: "describes an RBAC service role."

  - type: "service-role-binding"
    plural: "service-role-bindings"
    group: "rbac"
    version: "v1alpha1"
    messageName: "istio.rbac.v1alpha1.ServiceRoleBinding"
    collection: "istio/rbac/v1alpha1/servicerolebindings"
    description: "describes an RBAC service role."

  - type: "rbac-config"
    plural: "rbac-configs"
    group: "rbac"
    version: "v1alpha1"
    messageName: "istio.rbac.v1alpha1.RbacConfig"
    collection: "istio/rbac/v1alpha1/rbacconfigs"
    description: "describes the mesh level RBAC config.\n
                   Deprecated: use ClusterRbacConfig instead.\n
                   See https://github.com/istio/istio/issues/8825 for more details."

  - type: "cluster-rbac-config"
    plural: "clusterrbacconfigs"
    group: "rbac"
    version: "v1alpha1"
    messageName: "istio.rbac.v1alpha1.RbacConfig"
    collection: "istio/rbac/v1alpha1/clusterrbacconfigs"
    clusterScoped: true
    description: "describes the cluster level RBAC config."

  - type: "authorization-policy"
    plural: "authorizationpolicies"
    group: "security"
    version: "v1beta1"
    messageName: "istio.security.v1beta1.AuthorizationPolicy"
    collection: "istio/security/v1beta1/authorizationpolicies"
    description: "describes the authorization policy."

  - type: "request-authentication"
    plural: "requestauthentications"
    group: "security"
    version: "v1beta1"
    messageName: "istio.security.v1beta1.RequestAuthentication"
    collection: "istio/security/v1beta1/requestauthentications"
    validate: "ValidateRequestAuthentication"
    description: "describes the request authentication."
